/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */

export interface AlumnoProfesor {
  /** @nullable */
  asignatura?: string | null;
  /** @nullable */
  direccion?: string | null;
  /** @nullable */
  dni?: string | null;
  edad?: number;
  /** @nullable */
  email?: string | null;
  id?: number;
  matriculaId?: number;
  /** @nullable */
  nombre?: string | null;
}
