/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */
import type { Matricula } from './matricula';
import type { Profesor } from './profesor';

export interface Asignatura {
  creditos?: number;
  id?: number;
  /** @nullable */
  matriculas?: Matricula[] | null;
  /** @nullable */
  nombre?: string | null;
  /** @nullable */
  profesor?: string | null;
  profesorNavigation?: Profesor;
}
