/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */

export * from './alumno';
export * from './alumnoProfesor';
export * from './asignatura';
export * from './calificacion';
export * from './deleteApiEliminarAlumnoParams';
export * from './deleteApiEliminarCalificacionParams';
export * from './getApiAlumnoParams';
export * from './getApiAlumnosProfesorParams';
export * from './getApiCalificacionesParams';
export * from './matricula';
export * from './postApiAlumnoAsignaturaParams';
export * from './problemDetails';
export * from './profesor';