/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */
import type { Alumno } from './alumno';
import type { Asignatura } from './asignatura';
import type { Calificacion } from './calificacion';

export interface Matricula {
  alumno?: Alumno;
  alumnoId?: number;
  asignatura?: Asignatura;
  asignaturaId?: number;
  /** @nullable */
  calificacions?: Calificacion[] | null;
  id?: number;
}
