/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */

export interface ProblemDetails {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
  [key: string]: unknown;
}
