/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WebApi
 * OpenAPI spec version: 1.0
 */
import type { Asignatura } from './asignatura';

export interface Profesor {
  /** @nullable */
  asignaturas?: Asignatura[] | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  nombre?: string | null;
  /** @nullable */
  pass?: string | null;
  /** @nullable */
  usuario?: string | null;
}
